### ISSUE TITLE
Add CPHD, SICD, and SIDD to sar:product_type

### ISSUE THREAD

**Issue by jmorrison1847** [stac-extensions/sar#10]
I have actually two favors to ask:

1. One new `Type` called `Phase History` which is similar to, but not the same as, complex data
2. Three new `sar:product_type`:

- Compensated Phase History Data (CPHD) | Phase History
- Sensor Independent Complex Data (SICD) | Complex
- Sensor Independent Detected Data (SIDD) | Amplitude

Each of these is a very highly specified form of standard ("sensor independent") metadata requirements and organization created by the National Geospatial Intelligence Agency. You'll start to notice them in the API and product documentation for every commercial customer with aspirations to sell to them, and it would be wonderful to help encourage these organizations to use STAC.

**Comment by m-mohr** [comment]
Please note that the table in https://github.com/stac-extensions/sar#sarproduct_type is not meant to be exhaustive / complete, it is just a list of suggestions. But I'm happy to discuss and accept PRs with the community. :-)

**Comment by emmanuelmathot** [comment]
similar comment as per https://github.com/stac-extensions/sar/issues/9#issuecomment-1172046369.
I read about those sensor independent format some time ago and there are indeed interesting, especially in the ARD context.
IMO, It is worth to list them in the documentation but I'd like to have concrete samples to base STAC item examples on. @jmorrison1847, would you have some to recommend?

**Comment by jmorrison1847** [comment]
@emmanuelmathot apologies for the radio silence, I just forgot to check Github for a month. Showing my true colors...

A great example of this just happened in the time since posting it - Capella released sample data via AW that includes a collection of SICD files compliant with the STAC standard: [https://capella-open-data.s3.us-west-2.amazonaws.com/index.html/BrVjRL9LGRjg8ipuaKLhdHr1kD4sbvyd8QTYGwbMTTtkR4fzPd4yeiApxyrQkiq/2U5bjtVSEPJUkNoHyocrdciedbcheZ6VAXprFmxH5bwLpegLEXWtWg5fUM2VVpdMQjFW9FaKBeHy8hgyTZqF5Eiacgwn4vn3adb?t=2](url)

If that link is wonky, you can get to it by going to the main page on the AWS open data website and navigating to the STAC Catalog or STAC Browser on the right-hand side there: https://registry.opendata.aws/capella_opendata/
<img width="1220" alt="Screen Shot 2022-07-28 at 11 30 58 AM" src="https://user-images.githubusercontent.com/12401491/181577764-2aa5c371-2870-4f66-a139-3893c78fe23e.png">

**Comment by pmallas** [comment]
Well, this is probably going to open a can of worms, but does product type mean processing level or file format? Because a SICD is basically a SLC in NITF format. And a SIDD would be likely a GEC or GTC type product in NITF.  CPHD would be RAW (as S1 calls them).  I don't think these two things should be conflated.

**Comment by m-mohr** [comment]
Processing level!

File Format should be specified in the asset property `type`.

**Comment by emmanuelmathot** [comment]
Yes the `sar:product_type` is the combination of the SAR operating mode and the processing level. It should easily give information about the data you'll find inside (amplitude, phase...) and it's refining (raw, geocoded, terrain corrected...). So it is better if we keep using "common" types, especially for cross-mission search in the catalogs.

**Comment by m-mohr** [comment]
Closing in favor of #14
