### ISSUE TITLE
Stripmap Incidence angle at mid swath optional field

### ISSUE THREAD

**Issue by fabricebrito** [stac-extensions/sar#16]
We need to include an optional field for exposing the Incidence angle at mid swath for SAR acquisitions:

`sar:incidence_angle_mid_swath` a number expressed as degrees.

Would you be open for a PR with this?

**Comment by emmanuelmathot** [comment]
Isn't it something that can be set in the `view:incidence_angle` field and clarified that the value corresponds to the mid swath in this extension?

**Comment by m-mohr** [comment]
I agree with @emmanuelmathot, that's also what we do in CDSE.

**Comment by fabricebrito** [comment]
That's fair! Thanks!
