### ISSUE TITLE
Error in defining required fields

### ISSUE THREAD

**Issue by Dimplejain23** [stac-extensions/sar#4]
I am trying to add the SAR extension to sentinel-1 data, getting error while defining the required fields. Below given is code and error:
`item = pystac.Item(id=filename, 
                               geometry=footprint,
                               bbox=bbox,
                               datetime=utc_time,
                               properties={},
                               stac_extensions=[pystac.Extensions.SAR])`

`item.ext.sar.polarizations = ['VV']`

---> 33     item.ext.sar.polarizations = ['VV']

~/anaconda3/envs/stac-creation/lib/python3.7/site-packages/pystac/extensions/sar.py in polarizations(self, values)
    186         if not isinstance(values, list):
    187             raise pystac.STACError(f'polarizations must be a list. Invalid "{values}"')
--> 188         self.item.properties[POLARIZATIONS] = [v.value for v in values]
    189 
    190     @property

~/anaconda3/envs/stac-creation/lib/python3.7/site-packages/pystac/extensions/sar.py in <listcomp>(.0)
    186         if not isinstance(values, list):
    187             raise pystac.STACError(f'polarizations must be a list. Invalid "{values}"')
--> 188         self.item.properties[POLARIZATIONS] = [v.value for v in values]
    189 
    190     @property

AttributeError: 'str' object has no attribute 'value'

@matthewhanson @m-mohr @cholmes 
It would be very helpful if you suggest any documentation or example to adding SAR extension. Thank You

**Comment by m-mohr** [comment]
I think you would be better of asking this in the pystac issue tracker. This is the issue tracker for the implementation agnostic extension and I don't have a clue about pystac or python.
