### ISSUE TITLE
Azimuth- and Range resolution

### ISSUE THREAD

**Issue by maawoo** [stac-extensions/sar#6]
Hi all!
I was wondering how best to include `sar:resolution_range` & `sar:resolution_azimuth` for SLC data as it is dependent on the incidence angle as listed [here](https://sentinel.esa.int/web/sentinel/user-guides/sentinel-1-sar/resolutions/level-1-single-look-complex). The example provided in this repository is only for GRD, which is of course more straightforward. 

The description says "maximum ability to distinguish two adjacent targets", so in this case it would be the best resolution for a given range. However, I think this would be misleading for users who are not familiar with GRD and SLC resolutions.

**Comment by emmanuelmathot** [comment]
We use the best resolution of the maximum for range or azimuth of the entire scene. For Sentinel 1 for instance, here is our logic along with an example:

```csharp
private double GetGroundSampleDistance(string pt, string mode, string res)
        {
            if (pt == "RAW") return 0;
            if (pt == "GRD")
            {
                if (res == 'F' && mode == "SM") return 9;
                if (res == 'H')
                {
                    if (mode == "SM") return 23;
                    if (mode == "IW") return 22;
                    if (mode == "EW") return 50;
                }
                if (res == 'M')
                {
                    if (mode == "WV") return 25;
                    return 40;
                }
            }
            if (pt == "SLC")
            {
                if (mode == "SM") return 4.9;
                if (mode == "IW") return 22;
                if (mode == "EW") return 43;
                if (mode == "WV") return 4.8;
            }
            if (pt == "OCN") return 20000;

            return 0;
        }
```


https://gist.github.com/emmanuelmathot/3d210fb95adf86e4f4ea2a52bb09e7eb

**Comment by maawoo** [comment]
In the card4l extension both `sar:resolution_range` and `sar:resolution_azimuth` are being used. Since the latest update in the related specification documents, it is required to provide both per beam ID. No matter if SLC or GRD. 

I assume adjusting these fields is not so easily done, as @m-mohr has mentioned in another context already. I'm not sure how best to further procede with this, but I thought it makes sense to connect this issue with https://github.com/stac-extensions/card4l/issues/14 as a first step.
