### ISSUE TITLE
Should `sar:instrument_mode` allow array on collection level

### ISSUE THREAD

**Issue by dthiex** [stac-extensions/sar#7]
I think the `sar:instrument_mode` should allow on the collection level several values (array) and not only a string (e.g. `"sar:instrument_mode":["SM","IW","EW","WV"]`).

This is how it's currently in use by the [GEE Catalog](https://earthengine-stac.storage.googleapis.com/catalog/COPERNICUS_S1_GRD.json) and also how Sentinel Hub has their Sentinel-1 collection saved (as 1 collection including all instrument_modes).

On an item level allowing a string only makes sense.

**Comment by m-mohr** [comment]
That's already the case, you'd put it in the Collection summaries and there it can be an array.
